name: dart_chain_link
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: mark <mark.mclaren@mclarencollege.in>

environment:
  sdk: '>=2.4.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

dependencies:
  english_words: ^3.1.5
  math_expressions: ^1.1.1
  petitparser: ^2.4.0